apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}-azure-resource-limits-exporter
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
type: Opaque
data:
  AZURE_TENANT_ID: {{ .Values.azureCredentials.tenantId | b64enc }}
  AZURE_CLIENT_ID: {{ .Values.azureCredentials.clientId | b64enc }}
  AZURE_CLIENT_SECRET: {{ .Values.azureCredentials.clientSecret | b64enc }}
  SUBSCRIPTION_ID: {{ .Values.azureCredentials.subscriptionId | b64enc }}
  LOCATION:  {{ .Values.location | b64enc }}