apiVersion: v1
kind: Service
metadata:
  labels:
    app: azure-resource-limits-exporter
  name: azure-resource-limits-exporter
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: azure-resource-limits-exporter
  type: ClusterIP